root: /home/ssd/data
gpus: 4
num_workers: 4

net: lenet
dataset: hmdb51
model_base: "image"

lr:
  SGD: 0.001
  Adam: 0.001
lr_step_size: 30
lr_gamma: 0.1
optimizer: SGD
momentum: 0.9

batch_size: 16
epochs: 50
pretrain: False
debug: True
debug_size: 4

log_freq: 10
ckpt_freq: 2
ckpt_load: False
val_freq: 1