root: /home/ssd/data
gpus: [0,1,2,3]
#gpus: [0]
num_workers: 4

net: mvit
dataset: moma
model_base: "video"

# TODO: learning rate to revise based on batch size/epoches?
lr:
  SGD: 0.05
  adamw: 0.0002
lr_step_size: 30
lr_policy: 'cosine'
lr_gamma: 0.1
wd:
  SGD: 1e-4
  adamw: 0.05
optimizer: adamw
momentum: 0.9


batch_size: 8
epochs: 30
pretrain: False
frozen: False
debug: False
debug_size: 4

log_freq: 10
ckpt_freq: 2
ckpt_load: False
val_freq: 1

T: 16
tau: 4
fps: 30