root: /home/ssd/data
gpus: [0]
num_workers: 2

net: objectnet
dataset: moma
model_base: "object"

lr:
  SGD: 0.05
  Adam: 0.001
lr_step_size: 30
lr_policy: 'cosine'
lr_gamma: 0.1
wd:
  SGD: 1e-4
  Adam: 0.05
optimizer: SGD
momentum: 0.9
# TODO: add warmup


batch_size: 16
epochs: 20
pretrain: False
frozen: False
debug: True
debug_size: 4

log_freq: 10
ckpt_freq: 2
ckpt_load: False
val_freq: 1