root: /home/ssd/data
gpus: 1
num_workers: 4

net: slowfast
dataset: moma
model_base: "video"

lr:
  SGD: 0.05
  Adam: 0.001
lr_step_size: 30
lr_policy: 'cosine'
# TODO: add topK acc
lr_gamma: 0.1
wd: 1e-4
optimizer: SGD
momentum: 0.9
# TODO: add warmup


batch_size: 8
epochs: 30
pretrain: True
frozen: False
debug: False
debug_size: 4

log_freq: 10
ckpt_freq: 2
ckpt_load: False
val_freq: 1

T: 8
tau: 8
fps: 30
num_clips: 10
num_crops: 3
alpha: 4
